name: Add Comment to New Issue
on:
  issues:
    types:
      - opened

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Add a comment to the new issue
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issueNumber = context.issue.number;
            const commentBody = "Obrigado por criar essa issue! Vamos verificar isso em breve.";
            github.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
