name: Comentar

on:
  issues:
    types:
      - opened

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Comment on issue
      run: |
        echo 'oi' > comment.txt
        gh issue comment ${{ github.event.issue.number }} --body comment.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
