name: issue-checklist

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: ben-z/actions-comment-on-issue@1.0.3
      with:
        message: "Gentle reminder:\n* Did you go through all of the troubleshooting steps outlined in README.md?"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
